import { FlatCompat } from '@eslint/eslintrc';

const compat = new FlatCompat({ baseDirectory: import.meta.dirname });

/**
 * The project had no linter at all. `jsx-a11y` is here for a specific reason:
 * roughly half the accessibility defects this branch fixed by hand — an
 * `aria-label` on a role-less element, an input labelled only by its placeholder,
 * a heading level jump — are exactly what it catches automatically, and a rule is
 * how they stay fixed.
 */
const config = [
  // Registers the jsx-a11y plugin, among others; the rules below extend the
  // subset it turns on by default.
  ...compat.extends('next/core-web-vitals', 'next/typescript'),
  {
    ignores: [
      '.next/**',
      'node_modules/**',
      'responsive-audit-output/**',
      'next-env.d.ts',
      // Generated by scripts/build-image-variants.mjs.
      'lib/image-variants.ts'
    ]
  },
  {
    rules: {
      /**
       * Off deliberately. The site does not use next/image — Railway's build runs
       * before the schema push, and the image server is not worth the deploy
       * surface for a shop this size — so responsive variants are pre-generated
       * instead and resolved in ResilientImage. See README.
       */
      '@next/next/no-img-element': 'off',

      /**
       * Each of these corresponds to a defect fixed by hand on this branch, and is
       * on so it cannot come back: an aria-label on a role-less element that was
       * never exposed, an input labelled only by a placeholder, a heading level
       * jump, an anchor with no accessible name.
       */
      'jsx-a11y/aria-role': 'error',
      'jsx-a11y/role-supports-aria-props': 'error',
      'jsx-a11y/no-redundant-roles': 'error',
      'jsx-a11y/aria-props': 'error',
      'jsx-a11y/aria-proptypes': 'error',
      'jsx-a11y/anchor-has-content': 'error',
      'jsx-a11y/heading-has-content': 'error',
      'jsx-a11y/label-has-associated-control': 'warn',
      'jsx-a11y/no-noninteractive-element-to-interactive-role': 'warn',

      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' }
      ]
    }
  },
  {
    // Build and audit scripts are Node, not Next, and run outside the app.
    files: ['scripts/**/*.mjs', 'prisma/**/*.ts'],
    rules: {
      '@typescript-eslint/no-explicit-any': 'off',
      'no-console': 'off'
    }
  }
];

export default config;
