'use server';
import {redirect} from 'next/navigation';
import {revalidatePath} from 'next/cache';
import {ProductType} from '@prisma/client';
import {db} from '@/lib/db';
import {clearAdminSession,isAdmin,setAdminSession} from '@/lib/admin';
const text=(f:FormData,n:string)=>String(f.get(n)||'').trim();
const slugify=(v:string)=>v.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');
async function guard(){if(!await isAdmin())redirect('/admin')}
export async function loginAdmin(formData:FormData){const password=text(formData,'password');if(!process.env.ADMIN_PASSWORD||password!==process.env.ADMIN_PASSWORD)redirect('/admin?error=1');await setAdminSession();redirect('/admin')}
export async function logoutAdmin(){await clearAdminSession();redirect('/admin')}
export async function saveProduct(formData:FormData){await guard();const id=text(formData,'id');const name=text(formData,'name');const slug=slugify(text(formData,'slug')||name);const description=text(formData,'description');const priceCents=Math.round(Number(formData.get('price')||0)*100);const inventory=Math.max(0,Number(formData.get('inventory')||0));const type=text(formData,'type') as ProductType;const imageUrl=text(formData,'imageUrl')||null;if(!name||!slug||priceCents<0)return;const data={name,slug,description,priceCents,inventory,type,imageUrl,active:true};if(id)await db.product.update({where:{id},data});else await db.product.create({data});revalidatePath('/admin');revalidatePath('/shop')}
export async function updateOrder(formData:FormData){await guard();const id=text(formData,'id');const trackingNumber=text(formData,'trackingNumber')||null;const fulfilled=text(formData,'fulfilled')==='yes';await db.order.update({where:{id},data:{trackingNumber,status:fulfilled?'FULFILLED':'PAID'}});revalidatePath('/admin')}
export async function addClass(formData:FormData){await guard();await db.classEvent.create({data:{title:text(formData,'title'),description:text(formData,'description'),startsAt:new Date(text(formData,'startsAt')),location:text(formData,'location'),priceCents:Math.round(Number(formData.get('price')||0)*100),capacity:Number(formData.get('capacity')||12),imageUrl:text(formData,'imageUrl')||null}});revalidatePath('/admin');revalidatePath('/classes')}
export async function addGallery(formData:FormData){await guard();await db.galleryItem.create({data:{title:text(formData,'title'),caption:text(formData,'caption')||null,imageUrl:text(formData,'imageUrl'),sortOrder:Number(formData.get('sortOrder')||0)}});revalidatePath('/admin');revalidatePath('/gallery')}
export async function addAmazon(formData:FormData){await guard();await db.amazonPick.create({data:{title:text(formData,'title'),description:text(formData,'description')||null,imageUrl:text(formData,'imageUrl')||null,amazonUrl:text(formData,'amazonUrl'),category:text(formData,'category')||null,sortOrder:Number(formData.get('sortOrder')||0)}});revalidatePath('/admin');revalidatePath('/amazon')}
export async function addCareSheet(formData:FormData){await guard();const plantName=text(formData,'plantName');await db.careSheet.create({data:{plantName,slug:slugify(text(formData,'slug')||plantName),botanical:text(formData,'botanical')||null,summary:text(formData,'summary'),light:text(formData,'light'),water:text(formData,'water'),humidity:text(formData,'humidity'),soil:text(formData,'soil'),feeding:text(formData,'feeding'),temperature:text(formData,'temperature'),petSafety:text(formData,'petSafety')||null,tips:text(formData,'tips'),imageUrl:text(formData,'imageUrl')||null}});revalidatePath('/admin');revalidatePath('/care')}
