import Link from 'next/link';

const products=[['Hand-Potted Houseplants','Thoughtfully paired plants and planters, ready to brighten a home.','https://images.unsplash.com/photo-1485955900006-10f4d324d411?auto=format&fit=crop&w=900&q=80'],['Loose-Leaf Teas','Comforting tea blends and simple supplies for an everyday ritual.','https://images.unsplash.com/photo-1594631252845-29fc4cc8cde9?auto=format&fit=crop&w=900&q=80'],['Handmade Botanicals','Small-batch soaps and lotions inspired by garden ingredients.','https://images.unsplash.com/photo-1607006483225-3f4b5308f95d?auto=format&fit=crop&w=900&q=80']];
export default function Home(){return <>
<section className="hero"><div className="container hero-inner"><div className="eyebrow">Grow beautifully</div><h1>Plants, botanicals & a little know-how.</h1><p>The Hillside Gardens is Tammy Hill’s collection of living plants, comforting teas, handmade goods and practical plant education.</p><div className="actions"><Link className="btn gold" href="/shop">Explore the shop</Link><Link className="btn light" href="/classes">Join a planter class</Link></div></div></section>
<section className="section"><div className="container"><div className="sectionhead"><div className="eyebrow">From the hillside</div><h2>Things made to be enjoyed, shared & grown.</h2><p>Shop small-batch goods, discover a new plant, or learn how to build a planter you’ll be proud to take home.</p></div><div className="grid">{products.map(([t,d,i])=><article className="card" key={t}><img className="photo" src={i} alt=""/><div className="cardbody"><span className="pill">Hillside favorite</span><h3>{t}</h3><p>{d}</p><Link href="/shop"><b>Shop collection →</b></Link></div></article>)}</div></div></section>
<section className="section alt"><div className="container split"><img className="portrait" src="https://images.unsplash.com/photo-1416879595882-3373a0480b5b?auto=format&fit=crop&w=1100&q=85" alt="Lush potted garden plants"/><div><div className="eyebrow">Meet Tammy</div><h2>Helping people feel confident with plants.</h2><p className="quote">“You don’t need a green thumb. You just need to understand what your plant is asking for.”</p><p>Tammy Hill created The Hillside Gardens around a simple love of plants and sharing what she knows. Her hands-on planter classes make plant care approachable, social and fun.</p><div className="actions"><Link className="btn" href="/about">Read Tammy’s story</Link><Link className="btn" href="/care">Browse care sheets</Link></div></div></div></section>
<section className="section"><div className="container"><div className="sectionhead"><div className="eyebrow">Learn & grow</div><h2>Practical plant help, without the guesswork.</h2></div><div className="featuregrid">{[['Light made simple','Understand bright, indirect and low light.'],['Water with confidence','Learn when to water instead of following a rigid calendar.'],['Choose the right pot','Match drainage, size and soil to the plant.'],['Build beautiful planters','Learn combinations that look good and grow well together.']].map(([a,b])=><div className="feature" key={a}><b>{a}</b><span>{b}</span></div>)}</div></div></section>
<section className="section"><div className="container newsletter"><div><div className="eyebrow">The Hillside Notes</div><h3>Seasonal tips, class dates & new arrivals.</h3></div><a className="btn gold" href="mailto:hello@thehillsidegarden.com?subject=Join%20The%20Hillside%20Notes">Join the list</a></div></section>
</>}
