import { CareGuideType, Prisma } from '@prisma/client';

const houseplantImage =
  'https://images.unsplash.com/photo-1485955900006-10f4d324d411?auto=format&fit=crop&w=1400&q=88';
const foliageImage =
  'https://images.unsplash.com/photo-1497250681960-ef046c08a56e?auto=format&fit=crop&w=1400&q=88';
const pottingImage =
  'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?auto=format&fit=crop&w=1400&q=88';
const gardenImage =
  'https://images.unsplash.com/photo-1466692476868-aef1dfb1e735?auto=format&fit=crop&w=1400&q=88';

export const starterCareGuides = [
  {
    plantName: 'Monstera Deliciosa',
    slug: 'monstera-deliciosa',
    guideType: CareGuideType.PLANT,
    category: 'Tropical foliage',
    difficulty: 'Beginner friendly',
    botanical: 'Monstera deliciosa',
    summary: 'Iconic split foliage that grows best with bright filtered light, steady watering and room to climb.',
    light: 'Bright, indirect light. Gentle morning sun is usually fine; harsh afternoon sun can scorch leaves.',
    water: 'Water thoroughly when the top 2 inches of soil feel dry, then empty the saucer.',
    humidity: 'Average household humidity is acceptable; 45–65% supports larger, cleaner leaves.',
    soil: 'An airy aroid mix with potting soil, orchid bark and perlite or pumice.',
    feeding: 'Use a balanced fertilizer at half strength about monthly in spring and summer.',
    temperature: '65–85°F; protect from cold drafts and temperatures below about 55°F.',
    petSafety: 'Contains insoluble calcium oxalates and should be kept away from pets and children who may chew it.',
    tips: 'Rotate the pot every week or two and add a moss pole or sturdy support as the plant matures. Aerial roots may be guided toward the support or soil.',
    symptoms: 'Yellow lower leaves, brown edges, small unsplit new leaves, leaning growth or long spaces between leaves.',
    causes: 'Yellowing is often related to wet soil; small or unsplit leaves commonly indicate lower light or lack of climbing support.',
    treatment: 'Check soil moisture and roots before watering again, improve light gradually, and secure the main stem to a support without tying petioles tightly.',
    prevention: 'Use a draining pot, avoid watering by calendar alone, wipe leaves periodically and inspect new growth for pests.',
    checklist: 'Bright indirect light\nWater after the top 2 inches dry\nUse a chunky, well-draining mix\nProvide support for mature growth\nKeep away from chewing pets',
    imageUrl: 'https://images.unsplash.com/photo-1614594575810-51b862c2d7b6?auto=format&fit=crop&w=1400&q=88',
    featured: true,
    sortOrder: 1,
    published: true
  },
  {
    plantName: 'Golden Pothos',
    slug: 'golden-pothos',
    guideType: CareGuideType.PLANT,
    category: 'Trailing plants',
    difficulty: 'Excellent beginner plant',
    botanical: 'Epipremnum aureum',
    summary: 'A forgiving trailing classic that adapts to many homes and clearly shows when it needs water.',
    light: 'Low to bright indirect light. Brighter filtered light preserves stronger variegation and fuller growth.',
    water: 'Let the top 1–2 inches dry, then water fully. Slight leaf softening can be an early thirst signal.',
    humidity: 'Normal household humidity is usually sufficient.',
    soil: 'A standard indoor potting mix amended with perlite for drainage.',
    feeding: 'Monthly at half strength during active growth; little or no fertilizer is needed in winter.',
    temperature: '60–85°F; avoid cold windows and HVAC blasts.',
    petSafety: 'Toxic if chewed; keep trailing vines out of reach of pets and small children.',
    tips: 'Prune just above a node to encourage branching. Cuttings root easily in water or moist potting mix.',
    symptoms: 'Yellow leaves, black soft patches, sparse vines, fading variegation or crispy brown areas.',
    causes: 'Persistent wet soil causes most yellowing; low light creates sparse growth and weaker variegation.',
    treatment: 'Remove damaged leaves, correct watering, move gradually to brighter indirect light and trim long bare vines.',
    prevention: 'Use drainage, rotate the plant and check soil rather than relying on a fixed watering day.',
    checklist: 'Indirect light\nDry the top 1–2 inches between watering\nTrim vines for fullness\nRoot cuttings to fill the pot\nKeep away from chewing pets',
    imageUrl: 'https://images.unsplash.com/photo-1593691509543-c55fb32e5cee?auto=format&fit=crop&w=1400&q=88',
    featured: true,
    sortOrder: 2,
    published: true
  },
  {
    plantName: 'Snake Plant',
    slug: 'snake-plant',
    guideType: CareGuideType.PLANT,
    category: 'Low-maintenance plants',
    difficulty: 'Very easy',
    botanical: 'Dracaena trifasciata',
    summary: 'Architectural, drought-tolerant and dependable when protected from frequent watering and cold soil.',
    light: 'Tolerates low light but grows best in medium to bright indirect light.',
    water: 'Allow the soil to dry completely or nearly completely before watering again.',
    humidity: 'Average to dry indoor air is appropriate.',
    soil: 'Fast-draining cactus or succulent mix in a pot with a drainage hole.',
    feeding: 'Feed lightly two or three times during spring and summer.',
    temperature: '60–85°F; avoid prolonged cold and wet conditions.',
    petSafety: 'Mildly toxic if eaten and may cause gastrointestinal upset.',
    tips: 'Too much water is the primary risk. A heavy pot and damp soil are reasons to wait, not water.',
    symptoms: 'Mushy leaf bases, folding leaves, wrinkling, brown dry patches or a plant leaning out of wet soil.',
    causes: 'Mushy tissue usually means overwatering or cold damage; wrinkling with bone-dry soil indicates thirst.',
    treatment: 'Remove rotted sections, inspect rhizomes, repot into dry fast-draining mix and delay watering after repotting.',
    prevention: 'Use a snug draining pot, water less during winter and never leave the pot standing in water.',
    checklist: 'Let soil dry deeply\nUse succulent-style soil\nChoose a draining pot\nWater less in winter\nProtect from cold drafts',
    imageUrl: 'https://images.unsplash.com/photo-1593482892290-f54927ae2bb0?auto=format&fit=crop&w=1400&q=88',
    featured: true,
    sortOrder: 3,
    published: true
  },
  {
    plantName: 'ZZ Plant',
    slug: 'zz-plant',
    guideType: CareGuideType.PLANT,
    category: 'Low-maintenance plants',
    difficulty: 'Very easy',
    botanical: 'Zamioculcas zamiifolia',
    summary: 'Glossy, durable foliage with underground rhizomes that store water and reward a hands-off approach.',
    light: 'Low to bright indirect light. Avoid intense direct sun.',
    water: 'Allow most of the pot to dry before watering. The rhizomes store moisture for long periods.',
    humidity: 'Average household humidity is sufficient.',
    soil: 'A loose, well-draining indoor mix with added perlite or pumice.',
    feeding: 'Every 6–8 weeks during spring and summer at reduced strength.',
    temperature: '60–80°F.',
    petSafety: 'Toxic if chewed; sap may irritate sensitive skin.',
    tips: 'Use a pot with drainage and resist watering because the surface looks dry. Check moisture deeper in the pot.',
    symptoms: 'Yellowing stems, soft rhizomes, drooping from the base or wrinkled leaflets.',
    causes: 'Yellow stems and soft rhizomes generally point to prolonged wet soil. Wrinkled leaflets with very dry soil may indicate thirst.',
    treatment: 'Remove rot, allow healthy rhizomes to dry briefly, repot into fresh draining mix and reduce watering frequency.',
    prevention: 'Use a moisture check several inches deep and avoid oversized pots that stay wet too long.',
    checklist: 'Indirect light\nDry most of the pot between watering\nUse a draining mix\nAvoid oversized pots\nKeep away from pets',
    imageUrl: 'https://images.unsplash.com/photo-1632207691143-643e2a9a9361?auto=format&fit=crop&w=1400&q=88',
    sortOrder: 4,
    published: true
  },
  {
    plantName: 'Peace Lily',
    slug: 'peace-lily',
    guideType: CareGuideType.PLANT,
    category: 'Flowering houseplants',
    difficulty: 'Moderate',
    botanical: 'Spathiphyllum',
    summary: 'Elegant foliage and white blooms with visible thirst signals and a preference for even moisture.',
    light: 'Medium to bright indirect light. More filtered light generally supports more blooms.',
    water: 'Water when the upper inch begins to dry. Keep evenly moist but never waterlogged.',
    humidity: 'Prefers moderate to higher humidity and steady air circulation.',
    soil: 'Rich but well-draining indoor potting mix.',
    feeding: 'Monthly at half strength in spring and summer.',
    temperature: '65–80°F.',
    petSafety: 'Toxic to cats and dogs if chewed.',
    tips: 'Filtered or rainwater may reduce brown tips in homes with hard or heavily treated tap water.',
    symptoms: 'Dramatic drooping, brown tips, yellow lower leaves, no blooms or blackened roots.',
    causes: 'Drooping may be thirst, root stress or both. Brown tips can come from dry air, salts or inconsistent watering.',
    treatment: 'Check moisture before watering, flush accumulated salts, trim damaged tips and inspect roots if the plant stays limp in wet soil.',
    prevention: 'Maintain even moisture, avoid fertilizer buildup and keep the plant away from hot or cold air vents.',
    checklist: 'Medium-bright indirect light\nKeep lightly moist\nUse filtered water when possible\nProvide moderate humidity\nKeep away from pets',
    imageUrl: houseplantImage,
    sortOrder: 5,
    published: true
  },
  {
    plantName: 'Spider Plant',
    slug: 'spider-plant',
    guideType: CareGuideType.PLANT,
    category: 'Pet-friendlier plants',
    difficulty: 'Easy',
    botanical: 'Chlorophytum comosum',
    summary: 'Cheerful arching foliage that produces baby plantlets and adapts well to ordinary household conditions.',
    light: 'Medium to bright indirect light. Avoid prolonged harsh sun.',
    water: 'Water when the top inch dries; do not keep continuously soggy.',
    humidity: 'Average humidity works, though slightly higher humidity may reduce dry tips.',
    soil: 'Standard well-draining houseplant mix.',
    feeding: 'Monthly during spring and summer at half strength.',
    temperature: '60–80°F.',
    petSafety: 'Generally considered non-toxic, although chewing any plant can still cause stomach upset.',
    tips: 'Root plantlets in water or pin them directly into a small pot of moist soil while still attached to the parent.',
    symptoms: 'Brown tips, pale leaves, limp growth or a lack of plantlets.',
    causes: 'Salt buildup, inconsistent watering and very dry air often cause brown tips. Low light may reduce vigor and plantlet production.',
    treatment: 'Flush the pot, switch to filtered water if needed, improve indirect light and remove severely damaged leaves.',
    prevention: 'Avoid overfertilizing and keep watering reasonably consistent.',
    checklist: 'Bright indirect light\nWater when the top inch dries\nFlush salts periodically\nPropagate plantlets easily\nGenerally pet-friendlier',
    imageUrl: 'https://images.unsplash.com/photo-1572688484438-313a6e50c333?auto=format&fit=crop&w=1400&q=88',
    sortOrder: 6,
    published: true
  },
  {
    plantName: 'Heartleaf Philodendron',
    slug: 'heartleaf-philodendron',
    guideType: CareGuideType.PLANT,
    category: 'Trailing plants',
    difficulty: 'Easy',
    botanical: 'Philodendron hederaceum',
    summary: 'A soft, fast-growing vine that is easy to trim, train and propagate.',
    light: 'Medium to bright indirect light; tolerates lower light with slower, leggier growth.',
    water: 'Water when the top 1–2 inches dry.',
    humidity: 'Average household humidity is adequate; moderate humidity encourages lush growth.',
    soil: 'Airy, well-draining indoor mix.',
    feeding: 'Monthly in spring and summer at half strength.',
    temperature: '65–85°F.',
    petSafety: 'Toxic if chewed.',
    tips: 'Pin vines back into the pot or plant rooted cuttings around the edge to create a fuller basket.',
    symptoms: 'Long bare vines, small leaves, yellowing, soft stems or brown dry patches.',
    causes: 'Sparse growth usually indicates low light or lack of pruning; soft yellow growth often points to wet soil.',
    treatment: 'Prune to healthy nodes, root cuttings, improve light gradually and correct watering.',
    prevention: 'Rotate regularly, trim before vines become bare and use a potting mix that drains freely.',
    checklist: 'Medium-bright indirect light\nDry the top 1–2 inches\nPrune for fullness\nPropagate from nodes\nKeep away from pets',
    imageUrl: foliageImage,
    sortOrder: 7,
    published: true
  },
  {
    plantName: 'Fiddle Leaf Fig',
    slug: 'fiddle-leaf-fig',
    guideType: CareGuideType.PLANT,
    category: 'Statement plants',
    difficulty: 'Intermediate',
    botanical: 'Ficus lyrata',
    summary: 'A dramatic indoor tree that rewards strong light, stable placement and careful watering.',
    light: 'Very bright indirect light with some gentle direct morning sun.',
    water: 'Water thoroughly when the top 2–3 inches dry. Keep the pattern consistent without leaving soil wet.',
    humidity: 'Moderate humidity with airflow.',
    soil: 'Fast-draining indoor mix with bark and perlite.',
    feeding: 'Monthly in spring and summer with a balanced or foliage fertilizer.',
    temperature: '65–80°F with minimal drafts and temperature swings.',
    petSafety: 'Sap and foliage can irritate pets and people if ingested or handled repeatedly.',
    tips: 'Choose a bright location and avoid moving the plant frequently. Rotate a small amount every week for even growth.',
    symptoms: 'Brown spots, lower leaf drop, red pinprick marks on new leaves, leaning or slow growth.',
    causes: 'Dark spreading spots may indicate root stress; crisp tan areas often indicate dryness or sun stress. Small red marks can occur with moisture imbalance during leaf expansion.',
    treatment: 'Assess soil and roots, improve light, stabilize watering and remove only severely damaged leaves.',
    prevention: 'Use a draining pot, water deeply but less often, and keep conditions stable.',
    checklist: 'Very bright light\nStable location\nWater after top 2–3 inches dry\nAvoid cold drafts\nInspect roots when spotting spreads',
    imageUrl: houseplantImage,
    sortOrder: 8,
    published: true
  },
  {
    plantName: 'Rubber Plant',
    slug: 'rubber-plant',
    guideType: CareGuideType.PLANT,
    category: 'Statement plants',
    difficulty: 'Easy to moderate',
    botanical: 'Ficus elastica',
    summary: 'A sturdy indoor tree with polished leaves that responds well to bright light and measured watering.',
    light: 'Bright indirect light; variegated forms need especially strong filtered light.',
    water: 'Water when the top 2 inches dry.',
    humidity: 'Average indoor humidity with airflow.',
    soil: 'Well-draining indoor mix with perlite or bark.',
    feeding: 'Monthly during spring and summer.',
    temperature: '65–85°F.',
    petSafety: 'Milky sap can irritate skin and is toxic if eaten.',
    tips: 'Wipe the broad leaves gently and prune above a node to encourage branching. Wear gloves if sensitive to sap.',
    symptoms: 'Lower leaf drop, yellowing, curling leaves or pale variegation.',
    causes: 'Sudden environmental changes, wet soil, cold drafts and insufficient light are common triggers.',
    treatment: 'Stabilize placement, adjust watering and increase filtered light gradually.',
    prevention: 'Avoid moving it repeatedly and protect from cold windows and air-conditioning vents.',
    checklist: 'Bright indirect light\nWater after top 2 inches dry\nWipe leaves\nProtect from drafts\nHandle sap carefully',
    imageUrl: foliageImage,
    sortOrder: 9,
    published: true
  },
  {
    plantName: 'Chinese Evergreen',
    slug: 'chinese-evergreen',
    guideType: CareGuideType.PLANT,
    category: 'Low-light tolerant plants',
    difficulty: 'Easy',
    botanical: 'Aglaonema species and cultivars',
    summary: 'Colorful, adaptable foliage that tolerates medium and lower light better than many tropical plants.',
    light: 'Low to bright indirect light. Variegated and colorful cultivars need brighter filtered light.',
    water: 'Let the top 1–2 inches dry before watering.',
    humidity: 'Average humidity; avoid extremely dry hot air.',
    soil: 'Loose, well-draining indoor mix.',
    feeding: 'Every 4–6 weeks in spring and summer at half strength.',
    temperature: '65–80°F; protect from temperatures below about 60°F.',
    petSafety: 'Toxic if chewed.',
    tips: 'Keep it warm and avoid placing it against a cold winter window.',
    symptoms: 'Yellow leaves, brown patches, drooping or fading color.',
    causes: 'Wet soil, cold exposure and insufficient light for highly variegated cultivars are common causes.',
    treatment: 'Warm the location, correct watering and move colorful varieties to brighter indirect light.',
    prevention: 'Use drainage and keep temperatures steady.',
    checklist: 'Indirect light\nLet top soil dry\nKeep warm\nAvoid soggy soil\nKeep away from pets',
    imageUrl: houseplantImage,
    sortOrder: 10,
    published: true
  },
  {
    plantName: 'Calathea and Prayer Plants',
    slug: 'calathea-prayer-plants',
    guideType: CareGuideType.PLANT,
    category: 'Humidity-loving plants',
    difficulty: 'Intermediate',
    botanical: 'Goeppertia, Calathea and Maranta species',
    summary: 'Patterned foliage plants that prefer gentle light, even moisture, warmth and low-mineral water.',
    light: 'Medium to bright indirect light with no harsh midday sun.',
    water: 'Keep lightly and evenly moist, allowing only the surface to begin drying.',
    humidity: 'Prefer 50% or higher with gentle airflow.',
    soil: 'Moisture-retentive but airy mix with coco coir or peat, bark and perlite.',
    feeding: 'Lightly every 4–6 weeks in the growing season.',
    temperature: '65–80°F and away from drafts.',
    petSafety: 'Many commonly sold prayer plants are considered non-toxic, but identify the exact plant and confirm before relying on that status.',
    tips: 'Filtered, distilled or rainwater often reduces crispy edges caused by salts and additives in tap water.',
    symptoms: 'Curling leaves, crispy edges, faded pattern, yellowing or spider-mite webbing.',
    causes: 'Dry soil, low humidity, mineral-heavy water, excess sun and spider mites are common triggers.',
    treatment: 'Rehydrate evenly, improve humidity and airflow, switch water sources and inspect leaf undersides closely.',
    prevention: 'Avoid complete drying, keep foliage clean and inspect regularly for mites.',
    checklist: 'Gentle indirect light\nEven moisture\nFiltered water\nHigher humidity\nInspect for spider mites',
    imageUrl: foliageImage,
    sortOrder: 11,
    published: true
  },
  {
    plantName: 'Aloe Vera',
    slug: 'aloe-vera',
    guideType: CareGuideType.PLANT,
    category: 'Succulents',
    difficulty: 'Easy with enough light',
    botanical: 'Aloe vera',
    summary: 'A sun-loving succulent that needs bright light, a small draining pot and long dry intervals.',
    light: 'Very bright light with several hours of direct or near-direct sun after gradual acclimation.',
    water: 'Soak thoroughly, then allow the mix to dry completely before watering again.',
    humidity: 'Average to dry air.',
    soil: 'Gritty cactus or succulent mix.',
    feeding: 'Once or twice in spring and summer at low strength.',
    temperature: '60–85°F; protect from frost.',
    petSafety: 'Aloe latex and whole-leaf ingestion can be toxic to pets. Keep out of reach.',
    tips: 'A terracotta pot helps the mix dry. Increase sun gradually to avoid scorch.',
    symptoms: 'Soft translucent leaves, brown mushy bases, thin curling leaves or stretched pale growth.',
    causes: 'Softness generally means too much water; thin curling leaves may indicate prolonged dryness; stretching means insufficient light.',
    treatment: 'Remove rot, allow cuts to callus, repot dry and move gradually to stronger light.',
    prevention: 'Use a small draining pot and wait for complete drying.',
    checklist: 'Very bright light\nDry completely between watering\nUse gritty soil\nChoose a snug pot\nKeep away from pets',
    imageUrl: gardenImage,
    sortOrder: 12,
    published: true
  },
  {
    plantName: 'Jade Plant',
    slug: 'jade-plant',
    guideType: CareGuideType.PLANT,
    category: 'Succulents',
    difficulty: 'Easy with bright light',
    botanical: 'Crassula ovata',
    summary: 'A long-lived succulent shrub that develops a sturdy form with strong light and restrained watering.',
    light: 'Bright light with several hours of gentle direct sun after acclimation.',
    water: 'Allow the soil to dry fully, then water deeply.',
    humidity: 'Average to dry indoor air.',
    soil: 'Fast-draining succulent mix with mineral grit.',
    feeding: 'Lightly every 6–8 weeks in spring and summer.',
    temperature: '60–80°F; cooler winter nights are acceptable if soil stays dry.',
    petSafety: 'Toxic to cats and dogs if eaten.',
    tips: 'Prune above leaf pairs to encourage branching and rotate for an even, tree-like shape.',
    symptoms: 'Soft leaves, leaf drop, black stems, wrinkling or stretched growth.',
    causes: 'Wet soil causes soft tissue and drop; inadequate light causes stretching; prolonged drought causes wrinkling.',
    treatment: 'Correct watering, remove rot and improve light gradually.',
    prevention: 'Use a heavy draining pot and avoid frequent small sips of water.',
    checklist: 'Strong light\nDry fully between watering\nUse succulent mix\nPrune for shape\nKeep away from pets',
    imageUrl: gardenImage,
    sortOrder: 13,
    published: true
  },
  {
    plantName: 'Phalaenopsis Orchid',
    slug: 'phalaenopsis-orchid',
    guideType: CareGuideType.PLANT,
    category: 'Flowering houseplants',
    difficulty: 'Moderate',
    botanical: 'Phalaenopsis hybrids',
    summary: 'A long-blooming orchid that prefers airy roots, bright filtered light and a complete wet-to-nearly-dry cycle.',
    light: 'Bright indirect light, often near an east window or behind a sheer curtain.',
    water: 'Water when roots turn silvery and the bark is nearly dry; drain completely.',
    humidity: 'Moderate humidity with airflow around roots and leaves.',
    soil: 'Orchid bark or a purpose-made Phalaenopsis mix, never dense potting soil.',
    feeding: 'Weakly every 2–4 weeks during active growth, flushing with plain water regularly.',
    temperature: '65–82°F; a modest nighttime drop can help initiate flower spikes.',
    petSafety: 'Phalaenopsis orchids are generally considered non-toxic, but discourage chewing and confirm exact plant identification.',
    tips: 'Keep water out of the crown overnight and use a ventilated orchid pot so roots can breathe.',
    symptoms: 'Wrinkled leaves, mushy roots, bud blast, yellow leaves or no rebloom.',
    causes: 'Root loss can make a plant look thirsty even in wet media. Sudden temperature changes and dry air can cause buds to drop.',
    treatment: 'Inspect roots, trim hollow or mushy tissue, repot in fresh bark and stabilize conditions.',
    prevention: 'Use airy media, drain fully and avoid ice cubes as a watering method.',
    checklist: 'Bright filtered light\nWater silvery roots\nUse orchid bark\nKeep crown dry\nProvide airflow',
    imageUrl: houseplantImage,
    sortOrder: 14,
    published: true
  },

  {
    plantName: 'Houseplant Care Basics',
    slug: 'houseplant-care-basics',
    guideType: CareGuideType.GENERAL,
    category: 'Getting started',
    difficulty: 'Start here',
    summary: 'A practical framework for choosing the right location, watering correctly and noticing trouble before it becomes serious.',
    tips: 'Healthy plant care is mostly observation. Match the plant to the light you actually have, check soil before watering, use drainage and make one change at a time when troubleshooting.',
    checklist: 'Identify the plant\nObserve the light through a full day\nUse a pot with drainage\nCheck soil before watering\nInspect leaves and stems weekly\nQuarantine new plants\nChange one variable at a time',
    prevention: 'A short weekly check catches pests, dry soil, standing water and yellowing before the problem spreads.',
    imageUrl: houseplantImage,
    featured: true,
    sortOrder: 101,
    published: true
  },
  {
    plantName: 'Watering Houseplants 101',
    slug: 'watering-houseplants-101',
    guideType: CareGuideType.GENERAL,
    category: 'Watering',
    difficulty: 'Essential skill',
    summary: 'Learn how to decide when a plant needs water, how to water thoroughly and why a calendar alone is unreliable.',
    water: 'Insert a finger, wooden skewer or moisture probe to the depth appropriate for the plant. Consider pot weight, leaf firmness and how quickly the mix normally dries.',
    tips: 'When it is time to water, soak the entire root ball until excess drains freely. Discard runoff. Frequent small sips can leave dry pockets and encourage shallow roots.',
    causes: 'Watering needs change with light, season, pot size, soil, temperature, humidity and root health.',
    prevention: 'Group plants by moisture needs, learn the weight of a dry versus watered pot, and reduce frequency when light and growth slow.',
    checklist: 'Check below the surface\nLift the pot\nWater the whole root ball\nLet excess drain\nEmpty saucers\nRecheck before the next watering',
    imageUrl: gardenImage,
    featured: true,
    sortOrder: 102,
    published: true
  },
  {
    plantName: 'Understanding Indoor Light',
    slug: 'understanding-indoor-light',
    guideType: CareGuideType.GENERAL,
    category: 'Light',
    difficulty: 'Essential skill',
    summary: 'A clear guide to low, medium and bright indirect light, window direction and safe acclimation to direct sun.',
    light: 'Bright indirect light means a bright room near a window without hours of harsh sun directly striking the leaves. Low light means a plant can survive, not necessarily thrive.',
    tips: 'Watch the actual spot at several times of day. Move plants toward stronger light gradually over one to three weeks to prevent sunburn.',
    symptoms: 'Low light can cause slow growth, long spaces between leaves, leaning and loss of variegation. Too much direct sun can cause bleached or crisp patches.',
    prevention: 'Rotate plants, clean windows and leaves, and use a grow light when natural light is consistently inadequate.',
    checklist: 'Check window direction\nObserve direct sun hours\nMeasure distance from glass\nAcclimate gradually\nRotate regularly\nConsider a grow light',
    imageUrl: foliageImage,
    featured: true,
    sortOrder: 103,
    published: true
  },
  {
    plantName: 'Soil, Drainage and Choosing a Pot',
    slug: 'soil-drainage-and-pots',
    guideType: CareGuideType.GENERAL,
    category: 'Potting',
    difficulty: 'Core skill',
    summary: 'How soil texture, drainage holes and pot size work together to keep roots supplied with both water and oxygen.',
    soil: 'Most tropical houseplants need a mix that holds some moisture while still containing air. Bark, perlite, pumice and coarse coco chips increase structure and drainage.',
    tips: 'Choose a pot only 1–2 inches wider than the root ball for most plants. Decorative cachepots are fine when the plant remains in a draining inner pot.',
    causes: 'Oversized pots and dense mixes remain wet too long, which reduces oxygen around roots and raises the risk of rot.',
    prevention: 'Use drainage holes, match the mix to the plant and avoid packing soil tightly around roots.',
    checklist: 'Drainage hole present\nPot close to root-ball size\nMix suited to the plant\nAiry amendments included\nNo standing water in cachepot',
    imageUrl: pottingImage,
    featured: true,
    sortOrder: 104,
    published: true
  },
  {
    plantName: 'How and When to Repot',
    slug: 'how-and-when-to-repot',
    guideType: CareGuideType.GENERAL,
    category: 'Potting',
    difficulty: 'Core skill',
    summary: 'Repot for a reason—not simply because a plant has been in the same container for a certain number of months.',
    tips: 'Repot when roots circle densely, water rushes through without wetting the mix, soil has broken down, roots are unhealthy or the plant is physically unstable. Move up one pot size in most cases.',
    symptoms: 'Roots emerging heavily from drainage holes, water running straight through, chronic wilting despite proper watering or a top-heavy plant tipping over.',
    treatment: 'Loosen circling roots gently, remove dead roots, use fresh appropriate mix, water to settle and avoid strong fertilizer for several weeks.',
    prevention: 'Inspect roots before deciding. Some plants bloom or grow better slightly snug and do not need annual pot enlargement.',
    checklist: 'Confirm a reason to repot\nChoose one size larger\nPrepare fresh mix\nTrim only dead roots\nKeep the same planting depth\nAllow recovery in stable light',
    imageUrl: pottingImage,
    sortOrder: 105,
    published: true
  },
  {
    plantName: 'Fertilizing Without Overdoing It',
    slug: 'fertilizing-houseplants',
    guideType: CareGuideType.GENERAL,
    category: 'Nutrition',
    difficulty: 'Core skill',
    summary: 'Feed active growth lightly and consistently while avoiding salt buildup and the temptation to fertilize a stressed plant.',
    feeding: 'A balanced complete fertilizer at half the label strength is a reasonable starting point for many foliage plants during active growth.',
    tips: 'Fertilizer is not medicine. Correct light, watering and root problems first. Apply to moist soil and flush the pot with plain water periodically.',
    symptoms: 'White crust on soil, brown tips, sudden wilting after feeding, weak growth or pale new leaves.',
    causes: 'Excess concentration and salt accumulation can burn roots. Pale growth can also come from low light, damaged roots or unsuitable pH.',
    treatment: 'Stop feeding, flush the mix thoroughly and resume only after healthy growth returns.',
    prevention: 'Use measured dilution, feed less in winter and never double a missed application.',
    checklist: 'Feed only active healthy plants\nDilute carefully\nApply to moist soil\nFlush salts periodically\nReduce in winter',
    imageUrl: gardenImage,
    sortOrder: 106,
    published: true
  },
  {
    plantName: 'Humidity, Airflow and Leaf Care',
    slug: 'humidity-airflow-leaf-care',
    guideType: CareGuideType.GENERAL,
    category: 'Environment',
    difficulty: 'Helpful upgrade',
    summary: 'Humidity helps many tropical plants, but airflow and clean foliage are equally important for healthy indoor growth.',
    humidity: 'Many common tropical plants are comfortable around 40–60%. Calatheas, ferns and some orchids often appreciate more.',
    tips: 'A room humidifier is more effective than occasional misting. Keep leaves from remaining wet for long periods and provide gentle air movement.',
    symptoms: 'Crispy edges, tightly curled leaves, slow unfurling, mildew or recurring spider mites.',
    causes: 'Dry air can contribute to edge damage and mites; stagnant humid air can encourage fungal problems.',
    treatment: 'Adjust humidity gradually, clean foliage, separate crowded plants and improve gentle circulation.',
    prevention: 'Use a hygrometer, clean the humidifier and avoid placing plants directly in heater or air-conditioner airflow.',
    checklist: 'Measure humidity\nUse clean humidifier water\nProvide gentle airflow\nWipe dusty leaves\nAvoid constantly wet foliage',
    imageUrl: foliageImage,
    sortOrder: 107,
    published: true
  },
  {
    plantName: 'Propagation Basics',
    slug: 'houseplant-propagation-basics',
    guideType: CareGuideType.GENERAL,
    category: 'Propagation',
    difficulty: 'Beginner project',
    summary: 'A starter guide to node cuttings, division, offsets and the conditions that help new roots form.',
    tips: 'The correct method depends on the plant. Vining aroids need a node; snake plants can use leaf sections or division; spider plants make offsets; many succulents need a callused cutting.',
    treatment: 'Use clean tools, label cuttings, keep the medium lightly moist rather than soaked and provide warm bright indirect light.',
    prevention: 'Do not move a water-rooted cutting into soil too early. Several branching roots usually adapt better than one short root.',
    checklist: 'Identify the propagation method\nUse clean sharp tools\nInclude a node when required\nProvide warmth and indirect light\nKeep medium lightly moist\nPot after a usable root system forms',
    imageUrl: pottingImage,
    sortOrder: 108,
    published: true
  },

  {
    plantName: 'Why Are My Plant’s Leaves Turning Yellow?',
    slug: 'yellow-leaves',
    guideType: CareGuideType.PROBLEM,
    category: 'Leaf symptoms',
    difficulty: 'Common issue',
    summary: 'Yellow leaves are a symptom, not a diagnosis. Use soil moisture, leaf position and the pattern of yellowing to narrow the cause.',
    symptoms: 'One older lower leaf yellowing occasionally may be normal. Widespread yellowing, soft stems, wet soil, dry crisp tissue or pale new growth require closer attention.',
    causes: 'Common causes include overwatering, prolonged drought, root damage, low light, cold stress, nutrient imbalance, pests and normal aging.',
    treatment: 'Check soil and roots before adding water or fertilizer. Correct the most likely environmental cause, remove only fully yellow leaves and watch new growth for improvement.',
    prevention: 'Use drainage, match watering to soil moisture and light, and avoid changing several conditions at once.',
    tips: 'The leaf pattern matters: lower soft yellow leaves with wet soil often point to excess moisture, while yellowing with crisp dry tissue may point to drought.',
    checklist: 'Check soil depth\nInspect roots if soil stays wet\nNote which leaves are affected\nInspect for pests\nReview recent temperature or location changes\nWait for new growth before judging recovery',
    imageUrl: foliageImage,
    featured: true,
    sortOrder: 201,
    published: true
  },
  {
    plantName: 'Brown Tips and Crispy Leaf Edges',
    slug: 'brown-tips-crispy-edges',
    guideType: CareGuideType.PROBLEM,
    category: 'Leaf symptoms',
    difficulty: 'Common issue',
    summary: 'Crispy tips often reflect inconsistent moisture, dry air or mineral buildup rather than a single disease.',
    symptoms: 'Dry brown tips, tan margins, papery patches or edges that slowly spread inward.',
    causes: 'Inconsistent watering, very dry air, hard-water minerals, fertilizer salts, root crowding, sun scorch and cold or hot drafts are common causes.',
    treatment: 'Correct watering, flush the pot, improve humidity if appropriate, move away from extreme airflow and trim only dead tissue with clean scissors.',
    prevention: 'Use consistent care, dilute fertilizer, flush salts and use filtered water for sensitive plants.',
    tips: 'Damaged tissue will not turn green again. Judge success by whether new leaves emerge clean and damage stops spreading.',
    checklist: 'Check recent watering gaps\nReview fertilizer strength\nFlush accumulated salts\nMeasure humidity\nCheck for direct sun and HVAC airflow\nWatch new leaves',
    imageUrl: foliageImage,
    sortOrder: 202,
    published: true
  },
  {
    plantName: 'Drooping or Wilting Houseplants',
    slug: 'drooping-wilting-houseplants',
    guideType: CareGuideType.PROBLEM,
    category: 'Whole-plant symptoms',
    difficulty: 'Common issue',
    summary: 'A drooping plant can be thirsty, waterlogged, overheated, root-damaged or simply adjusting—check before watering automatically.',
    symptoms: 'Limp leaves, collapsed stems, soft growth or a plant that does not recover after watering.',
    causes: 'Dry soil, saturated oxygen-poor soil, root rot, heat, cold, transplant shock and stem damage can all cause wilting.',
    treatment: 'Feel the soil deeply. Water thoroughly only when dry; if wet, inspect drainage and roots. Move the plant out of extreme heat or cold and support damaged stems.',
    prevention: 'Learn the normal weight and moisture pattern of the pot and avoid leaving roots in standing water.',
    tips: 'A thirsty plant often improves within hours after a proper watering. A plant that stays wilted in wet soil needs root inspection, not more water.',
    checklist: 'Check soil before watering\nLift the pot\nInspect drainage\nReview heat and cold exposure\nCheck roots if wet and wilted\nAllow recovery before fertilizing',
    imageUrl: houseplantImage,
    featured: true,
    sortOrder: 203,
    published: true
  },
  {
    plantName: 'Curling Leaves',
    slug: 'curling-leaves',
    guideType: CareGuideType.PROBLEM,
    category: 'Leaf symptoms',
    difficulty: 'Common issue',
    summary: 'Leaf curl is a protective response that may be triggered by moisture stress, temperature, light, pests or mineral-heavy water.',
    symptoms: 'Leaves folding inward, rolling at the edges, cupping upward or failing to unfurl normally.',
    causes: 'Dry soil, damaged roots, low humidity, excess sun, cold drafts, heat and pests—especially spider mites or thrips—are common causes.',
    treatment: 'Check soil, inspect both sides of leaves, stabilize temperature, adjust light and improve humidity only when the plant prefers it.',
    prevention: 'Avoid extreme drying, keep sensitive plants away from vents and inspect new leaves before they fully unfurl.',
    tips: 'Do not diagnose curl from humidity alone. Root and pest problems can look similar and require different treatment.',
    checklist: 'Check soil moisture\nInspect leaf undersides\nLook inside new growth\nReview sun exposure\nCheck temperature and airflow\nIdentify the plant’s humidity preference',
    imageUrl: foliageImage,
    sortOrder: 204,
    published: true
  },
  {
    plantName: 'Leggy Growth and Small Leaves',
    slug: 'leggy-growth-small-leaves',
    guideType: CareGuideType.PROBLEM,
    category: 'Growth problems',
    difficulty: 'Common issue',
    summary: 'Long spaces between leaves, leaning stems and smaller new foliage usually mean the plant needs stronger light or support.',
    symptoms: 'Long internodes, sparse vines, pale growth, leaning toward a window, smaller leaves or loss of variegation.',
    causes: 'Insufficient light is most common. Some climbing plants also make smaller leaves when allowed to trail without support.',
    treatment: 'Move gradually to brighter indirect light, add a suitable grow light, prune back bare growth and provide a climbing support when appropriate.',
    prevention: 'Rotate plants, clean windows and leaves, and position grow lights close enough to be useful without overheating foliage.',
    tips: 'Existing stretched stems will not shorten. Pruning and improved light encourage more compact replacement growth.',
    checklist: 'Increase light gradually\nRotate the pot\nPrune above healthy nodes\nRoot cuttings to refill the pot\nAdd support for climbing species',
    imageUrl: houseplantImage,
    sortOrder: 205,
    published: true
  },
  {
    plantName: 'Root Rot: Signs, Rescue and Prevention',
    slug: 'root-rot',
    guideType: CareGuideType.PROBLEM,
    category: 'Root problems',
    difficulty: 'Urgent issue',
    summary: 'Root rot develops when roots remain oxygen-starved and damaged, often in wet dense soil or an oversized container.',
    symptoms: 'Persistent wilting in wet soil, widespread yellowing, a sour smell, black or brown mushy roots, soft stems or leaves dropping easily.',
    causes: 'Frequent watering, poor drainage, dense decomposed mix, cold wet soil, an oversized pot or roots already damaged by disease or stress.',
    treatment: 'Unpot the plant, rinse or loosen soil, remove mushy roots with sterile tools, sanitize the pot, repot into fresh airy mix and water cautiously while new roots form.',
    prevention: 'Use drainage, choose an appropriate pot size, check moisture below the surface and adjust watering when light or temperature changes.',
    tips: 'Healthy roots are generally firm. Color varies by species, so texture and smell are more reliable than color alone.',
    checklist: 'Isolate the plant\nInspect roots\nRemove mushy tissue\nSanitize tools and pot\nUse fresh airy mix\nReduce watering during recovery\nPropagate healthy pieces as backup',
    imageUrl: pottingImage,
    featured: true,
    sortOrder: 206,
    published: true
  },
  {
    plantName: 'Fungus Gnats',
    slug: 'fungus-gnats',
    guideType: CareGuideType.PROBLEM,
    category: 'Pests',
    difficulty: 'Manageable pest',
    summary: 'Small dark flies around moist potting soil are usually fungus gnats. Control requires addressing both adults and soil-dwelling larvae.',
    symptoms: 'Tiny mosquito-like adults near pots, larvae in the upper soil and recurring activity after watering.',
    causes: 'Continuously moist organic potting mix supports fungus and larvae. New soil or plants may introduce them.',
    treatment: 'Allow the surface to dry as the plant permits, use yellow sticky cards for adults and apply a labeled biological larvicide such as Bacillus thuringiensis israelensis according to directions.',
    prevention: 'Quarantine new plants, avoid chronically wet soil, store potting mix sealed and clean fallen organic debris.',
    tips: 'Sticky cards show whether adults are decreasing but do not eliminate larvae by themselves. Repeat the larval treatment through the life cycle.',
    checklist: 'Isolate heavily affected pots\nPlace yellow sticky cards\nReduce unnecessary moisture\nTreat larvae with a labeled product\nRepeat as directed\nInspect nearby plants',
    imageUrl: pottingImage,
    featured: true,
    sortOrder: 207,
    published: true
  },
  {
    plantName: 'Spider Mites',
    slug: 'spider-mites',
    guideType: CareGuideType.PROBLEM,
    category: 'Pests',
    difficulty: 'Persistent pest',
    summary: 'Spider mites are tiny sap-feeding pests that cause stippling, dull foliage and fine webbing, especially in warm dry conditions.',
    symptoms: 'Fine pale speckling, dusty-looking leaves, webbing at leaf joints, fading color and mites visible as moving dots under magnification.',
    causes: 'Infested new plants, warm dry air and delayed detection allow populations to grow quickly.',
    treatment: 'Isolate the plant, rinse foliage thoroughly, remove heavily damaged leaves and apply an appropriately labeled miticide or insecticidal soap with complete coverage and repeated treatment as directed.',
    prevention: 'Inspect leaf undersides weekly, quarantine new plants, clean dusty foliage and avoid placing susceptible plants in hot dry airflow.',
    tips: 'Many ordinary insecticides do not control mites. Use a product specifically labeled for spider mites and follow the label exactly.',
    checklist: 'Isolate immediately\nInspect with bright light\nRinse both leaf surfaces\nTreat with a mite-labeled product\nRepeat per label\nCheck all nearby plants',
    imageUrl: foliageImage,
    featured: true,
    sortOrder: 208,
    published: true
  },
  {
    plantName: 'Mealybugs and Scale',
    slug: 'mealybugs-and-scale',
    guideType: CareGuideType.PROBLEM,
    category: 'Pests',
    difficulty: 'Persistent pest',
    summary: 'Cottony clusters or fixed brown bumps can signal mealybugs or scale insects hiding along stems, leaf joints and roots.',
    symptoms: 'White cottony material, sticky honeydew, sooty residue, brown shell-like bumps, yellowing and distorted new growth.',
    causes: 'New plants are the most common source. Dense growth and hidden leaf joints make early infestations easy to miss.',
    treatment: 'Isolate, remove visible pests with a cotton swab and rubbing alcohol where plant-safe, rinse, prune severe areas and use a labeled horticultural oil, soap or systemic option as appropriate and legal in your area.',
    prevention: 'Quarantine new plants, inspect stems and leaf axils, and clean tools between plants.',
    tips: 'Test any spray on a small area first. Repeated inspection is necessary because eggs and hidden pests can survive one treatment.',
    checklist: 'Isolate the plant\nInspect stems and leaf joints\nRemove visible pests\nApply a labeled treatment\nRepeat on schedule\nCheck roots if pests return',
    imageUrl: foliageImage,
    sortOrder: 209,
    published: true
  },
  {
    plantName: 'Mold, Mushrooms or Algae on Potting Soil',
    slug: 'mold-mushrooms-algae-on-soil',
    guideType: CareGuideType.PROBLEM,
    category: 'Soil problems',
    difficulty: 'Usually manageable',
    summary: 'Surface mold, algae or mushrooms usually indicate moisture and organic matter; the more important question is whether the roots are also staying too wet.',
    symptoms: 'White fuzzy growth, green film, mushrooms, musty odor or a crust on the soil surface.',
    causes: 'Wet soil, low airflow, decomposing organic material, contaminated tools or mineral and fertilizer deposits.',
    treatment: 'Remove surface growth and debris, improve airflow, let the mix dry appropriately and repot if the soil is dense, sour-smelling or roots are unhealthy.',
    prevention: 'Use clean pots and tools, avoid standing water, provide airflow and do not add household food scraps to indoor pots.',
    tips: 'Many surface fungi are not directly harmful, but they can be a useful warning that the pot stays moist longer than expected.',
    checklist: 'Check soil depth\nSmell the root zone\nRemove surface growth\nImprove airflow\nReduce unnecessary moisture\nInspect roots if the plant is declining',
    imageUrl: pottingImage,
    sortOrder: 210,
    published: true
  },

  {
    plantName: 'Spring Houseplant Reset',
    slug: 'spring-houseplant-reset',
    guideType: CareGuideType.SEASONAL,
    category: 'Spring',
    difficulty: 'Seasonal checklist',
    summary: 'Use increasing spring light and new growth as a cue to reassess watering, pruning, feeding, repotting and pest prevention.',
    tips: 'Clean leaves and windows, rotate plants, prune weak growth, inspect roots before repotting and restart fertilizer gradually only when active growth is visible.',
    prevention: 'Quarantine new spring purchases and inspect the entire collection before moving plants closer together.',
    checklist: 'Inspect for pests\nClean leaves and windows\nAdjust watering gradually\nPrune weak growth\nRepot only when needed\nRestart fertilizer lightly\nRefresh sticky traps',
    imageUrl: gardenImage,
    sortOrder: 301,
    published: true
  },
  {
    plantName: 'Summer Heat and Vacation Care',
    slug: 'summer-heat-vacation-care',
    guideType: CareGuideType.SEASONAL,
    category: 'Summer',
    difficulty: 'Seasonal checklist',
    summary: 'Prepare plants for faster drying, stronger sun, air-conditioning and time away without overwatering before a trip.',
    tips: 'Move sensitive plants back from intense glass, water normally before leaving, group compatible plants, close sheer curtains and test any self-watering setup before the trip.',
    symptoms: 'Rapid drying, sun scorch, collapsed leaves, hot root zones or cold damage from air-conditioning.',
    prevention: 'Do not leave pots standing in deep water. Ask a helper to check only the plants that truly need attention and leave written instructions.',
    checklist: 'Check afternoon sun\nMove plants from hot glass\nWater normally before travel\nGroup by moisture needs\nTest watering devices early\nLeave clear instructions\nKeep away from direct AC',
    imageUrl: gardenImage,
    sortOrder: 302,
    published: true
  },
  {
    plantName: 'Fall Transition for Indoor Plants',
    slug: 'fall-houseplant-transition',
    guideType: CareGuideType.SEASONAL,
    category: 'Fall',
    difficulty: 'Seasonal checklist',
    summary: 'As days shorten, help plants adjust by reducing fertilizer, spacing watering farther apart and inspecting anything moving indoors.',
    tips: 'Wash and quarantine outdoor plants before bringing them inside. Increase indoor light where possible and avoid abrupt exposure to heating vents.',
    prevention: 'Treat confirmed pests before plants rejoin the indoor collection and clean saucers, pots and leaf debris.',
    checklist: 'Inspect outdoor plants closely\nQuarantine indoors\nClean pots and foliage\nIncrease available light\nReduce fertilizer\nReassess watering intervals\nMove away from heating vents',
    imageUrl: foliageImage,
    sortOrder: 303,
    published: true
  },
  {
    plantName: 'Winter Houseplant Care',
    slug: 'winter-houseplant-care',
    guideType: CareGuideType.SEASONAL,
    category: 'Winter',
    difficulty: 'Seasonal checklist',
    summary: 'Lower light and slower growth usually mean less frequent watering, little fertilizer and extra attention to cold glass and dry heated air.',
    tips: 'Move plants to the brightest appropriate location, wipe leaves, rotate regularly and check soil more deeply before watering. Use a grow light when natural light is insufficient.',
    symptoms: 'Slow growth, lower leaf drop, stretching, cold damage, crispy edges or soil that stays wet much longer than it did in summer.',
    prevention: 'Keep foliage from touching cold windows, avoid placing plants directly over heat vents and pause routine feeding unless the plant is actively growing under strong light.',
    checklist: 'Maximize safe light\nWater less often\nPause or reduce fertilizer\nProtect from cold windows\nAvoid direct heat vents\nMonitor humidity and pests\nUse grow lights when needed',
    imageUrl: houseplantImage,
    featured: true,
    sortOrder: 304,
    published: true
  }
] satisfies Prisma.CareSheetUncheckedCreateInput[];

export function careGuideTypeLabel(type: CareGuideType | string) {
  if (type === CareGuideType.GENERAL) return 'Plant care basics';
  if (type === CareGuideType.PROBLEM) return 'Common issue';
  if (type === CareGuideType.SEASONAL) return 'Seasonal care';
  return 'Plant profile';
}
