/**
 * Generated by scripts/build-image-variants.mjs — do not edit by hand.
 *
 * Maps a public image path to the widths that exist beside it, so
 * lib/image-srcset.ts can build a srcset without touching the filesystem at
 * request time. Run `npm run images:variants` after adding photography.
 */
export const IMAGE_VARIANTS: Record<string, number[]> = {
  "/images/catalog/air-plants.webp": [
    400,
    800,
    1200,
    1600
  ],
  "/images/catalog/apothecary.webp": [
    400,
    800,
    1200,
    1600
  ],
  "/images/catalog/carnivorous-plants.webp": [
    400,
    800,
    1200,
    1600
  ],
  "/images/catalog/driftwood.webp": [
    400,
    800,
    1200,
    1600
  ],
  "/images/catalog/homemade-soaps.webp": [
    400,
    800,
    1200,
    1600
  ],
  "/images/catalog/house-plants.webp": [
    400,
    800,
    1200,
    1600
  ],
  "/images/catalog/live-plant-planters.webp": [
    400,
    800,
    1200,
    1600
  ],
  "/images/catalog/moss.webp": [
    400,
    800,
    1200,
    1600
  ],
  "/images/catalog/succulents.webp": [
    400,
    800,
    1200,
    1600
  ],
  "/images/catalog/terrarium-supplies.webp": [
    400,
    800,
    1200,
    1600
  ],
  "/images/gallery/patio-containers.webp": [
    400,
    800,
    1200,
    1600
  ],
  "/images/gallery/porch-planter.webp": [
    400,
    800,
    1200,
    1600
  ],
  "/images/gallery/soft-greens.webp": [
    400,
    800,
    1200,
    1600
  ],
  "/images/scenes/hillside-hero.webp": [
    400,
    800,
    1200,
    1600
  ],
  "/images/scenes/potting-bench.webp": [
    400,
    800,
    1200,
    1600
  ],
  "/images/scenes/workshop-table.webp": [
    400,
    800,
    1200,
    1600
  ]
};
